name: ndk_nwc
description: Nostr Wallet Connect
version: 0.2.0-dev001
homepage: https://github.com/relaystr/ndk

environment:
  sdk: ">=3.4.0 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  equatable: ^2.0.7
  ndk: ^0.2.0-dev001

dev_dependencies:
  test: any
