name: deploy docs to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
  #release:
  #  types: [ published ]

jobs:
  publish:
    name: Publish to gh-pages branch

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - uses: retypeapp/action-build@latest

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
          branch: gh-pages