name: tests
on: [push, workflow_dispatch]
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/ndk
    steps:
      - uses: actions/checkout@v1
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart format --output=none .
      - run: dart analyze --no-fatal-warnings
      - run: dart test --coverage="coverage"
      - run: dart test ./example
      - run: dart pub global activate coverage
      - run: $HOME/.pub-cache/bin/format_coverage --lcov --in=coverage --out=coverage.lcov --report-on=lib
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage.lcov
          verbose: true # optional (default = false)
